name: fe
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.2
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.2
  particles_flutter: ^0.1.1
  animated_background: ^2.0.0
  url_launcher: ^6.2.4
  go_router: ^14.1.0
  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: ^6.0.0
  socket_io_client: ^2.0.3
  timeago: ^3.6.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
